version: "3.9"
services:
  unbound:
    image: nodecloud/unbound:latest
    container_name: unbound
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always
    privileged: true
    depends_on:
      - redis
    volumes:
      - "./config:/etc/unbound"
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --save 43200 1 7200 100 --loglevel warning --rdbchecksum no --io-threads 4 --io-threads-do-reads yes
    volumes:
      - "redis-data:/data"
    restart: always
volumes:
  redis-data: