version: "3.9"
services:
  unbound:
    image: nodecloud/unbound:latest
    container_name: unbound
    network_mode: host
    restart: always
    privileged: true
    depends_on:
      - redis
    volumes:
      - "./config:/etc/unbound"
  easymosdns:
    image: nodecloud/easymosdns:latest
    container_name: easymosdns
    network_mode: host
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    network_mode: host
    command: redis-server --bind 127.0.0.1 --save 43200 1 7200 100 --loglevel warning --rdbchecksum no --io-threads 4 --io-threads-do-reads yes
    volumes:
      - "redis-data:/data"
    restart: always
volumes:
  redis-data: